version: "2"

services:
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: onelove@mysql
      MYSQL_DATABASE: onelove
      MYSQL_USER: userrone
      MYSQL_PASSWORD: mysql@onelove
    ports:
      - "3306:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
